// <auto-generated />
using DemoAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoAPI.Migrations
{
    [DbContext(typeof(DemoAngu_DBContext))]
    [Migration("20230217024735_Init2")]
    partial class Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoAPI.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "All kinds of books related to business and investing: management, finance, entrepreneurs, startup, skills, sales, etc",
                            name = "Business & Economics",
                            price = 23000,
                            quantity = 300
                        },
                        new
                        {
                            id = 2,
                            description = "All kinds of books for children to learn, entertain and have fun such as graphic books, children stories, fairy tales, comics, etc.",
                            name = "Children's Books",
                            price = 240000,
                            quantity = 20
                        },
                        new
                        {
                            id = 3,
                            description = "Fictions, novels, chicklit, poem and more",
                            name = "Fiction - Literature",
                            price = 20000,
                            quantity = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
